net stop OracleOraDb11g_home1TNSListener
net stop OracleMTSRecoveryService
net stop OracleServiceORCLTESTDB
net stop OracleDBConsoleOrclTestDB
net stop OracleRemExecService
net stop ReportServer$TOASQL
net stop SQLBrowser
net stop SQLWriter
net stop MSSQLFDLauncher$TOASQL
net stop MSSQL$TOASQL
net stop LSPSERVICE_MR
